name: Blog Posts

on:
  # Run workflow automatically
  schedule:
    # Runs every hour, on the hour
    - cron: '20 */8 * * *'  # 每八小时执行一次
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          # comma-separated list of RSS feed urls
          comment_tag_name: "STACKOVERFLOW"
          feed_list: "http://blog.ynxiu.com/atom.xml,https://feed.cnblogs.com/blog/u/308165/rss/"
          template: "<tr><td>$title</td><td>$url</td></tr>"
          max_post_count: 5
