name: This repo has x stars y forks


on:
  push:
    branches:
      - master
  fork:
  watch:
    types:
      - started
  schedule:
    - cron: '0 */8 * * *'  # 每八小时执行一次    
  workflow_dispatch: # 手动触发工作流

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: This repo has x stars y forks
        uses: ouuan/This-repo-has-x-stars-y-forks-action@v2
        with:          
          token: ${{ secrets.ACCESS_TOKEN }}
          template: "A profile README with <starCount> stars and <forkCount> forks"
